#!/usr/bin/env python

from toilet.indicator import ToiletIndicator
from toilet.toilet import Toilet
from toilet.dataloader import Dataloader

toilets = {
    'women': Toilet('Women', 'captor2', True),
    'men':   Toilet('Men', 'captor1', True)
}
ToiletIndicator(toilets, Dataloader())
